### ISSUE TITLE
Why different repository ?

### ISSUE THREAD

**Issue by atakanyenel** [russross/blackfriday-tool#12]
Hi,
I'm looking for best practices in Go as I'm learning it now. You have many projects in Go. I saw your `blackfriday` repository from the Heroku Golang app ( Good Job by the Way 👍 ) I have a question: 

Why did you created a new repo for the command line tool and didn't add it as a `cli` to your already existing blackfriday repo ? Is there a Golang related reason for that or some software engineering practice that you like ?

Sorry that I couldn't reach you in a more private way :octocat:

**Comment by russross** [comment]
I didn't have any particularly interesting reason for splitting the CLI into its own project. There was no pattern established for setting up repositories like this (`blackfriday` is pretty old--it came out before Go 1 and there were not many examples to copy), and I did not like the approaches I tried. For example, I had it in a subdirectory called `blackfriday/cli`, but then it naturally compiled into an executable called `cli` and that seemed ugly. So part of it was just lack of imagination on my part.

I guessed that command-line tool users would be a small percentage of overall users (most would use the library in a larger project) and I didn't want to clutter people's projects with code they would never use. I also thought that if the CLI got any kind of serious development, it might make sense to version it separately from the library. Those turned out to be weak reasons, since the CLI source is pretty small and has had very little development activity.

So there is probably not much to learn from this example, sorry! I tend to work mostly on projects where I am the only developer (I am a CS professor and mostly write code when I need something), so I have put much less thought than others into project structure and library organization.
